version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
          dependency-file: ./validation/python/requirements.txt
      - python/save-cache
      - run:
          command: ./validation/python/runtests.py
          name: Run ninjs unit tests

workflows:
  main:
    jobs:
      - build-and-test
