version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r validation/python/requirements.txt
      - python/save-cache
      - run:
          command: validation/python/runtests.py
          name: Run ninjs unit tests using Python jsonschema

workflows:
  main:
    jobs:
      - build-and-test
